## Slice
row_start: 0
#row_end: 100000 # (-1 for all)
row_end: -1 # (-1 for all)

## preprocess
min_speed: 0.01

renames:
  Tidpunkt [UTC]: time
  UTC time: time 
  Latitud (deg): latitude
  Latitude (deg): latitude
  Longitud (deg): longitude
  Longitude (deg): longitude
  Fart över grund (kts): sog
  Speed over ground (kts): sog
  Stävad kurs (deg): heading
  Heading (deg): heading
  Effekt EM Thruster 1 (kW): P1
  Effekt EM Thruster 2 (kW): P2
  Effekt EM Thruster 3 (kW): P3
  Effekt EM Thruster 4 (kW): P4
  Effekt EM Thruster Total (kW): P 
  Kurs över grund (deg): cog
  Course over ground (deg): cog
  Sin EM1 (): sin_pm1
  Sin EM2 (): sin_pm2 
  Sin EM3 (): sin_pm3
  Sin EM4 (): sin_pm4
  Cos EM1 (): cos_pm1
  Cos EM2 (): cos_pm2
  Cos EM3 (): cos_pm3
  Cos EM4 (): cos_pm4
  Thruster angle 1 (deg): delta1
  Thruster angle 2 (deg): delta2
  Relativ vindhastighet (m/s): aw
  Apparent wind speed (m/s): aw
  Relativ vindriktning (deg): awa
  Apparent wind direction (deg): awa
  Vindhastighet (m/s): w 
  Vindriktning (deg): wa

## preprocess_trip_numbering:
initial_speed_separator: 0.05
do_calculate_rudder_angles: False


## preprocess_trip_numbering
start_number: 0
trip_separator: 0 days 00:00:20

## Clean statistics:
min_distance: 4000
min_time: 700

min_distance: 7000
min_time: 1200
min_distance_uraniborg: 4000
min_time_uraniborg: 700


## clean_thrusters_node
P_max_ratio_diff: 0.3
cos_ratio_diff: 0.3

